<?xml version="1.0"?>
<package format="3">
  <name>boson_camera</name>
  <version>0.0.1</version>
  <description>ROS2 Wrapper for the FLIR Boson 640 Camera</description>
  <maintainer email="shenbax@seas.upenn.edu">Shenbagaraj Kannapiran</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>image_transport</depend>
  <depend>camera_info_manager</depend>
  <depend>cv_bridge</depend>
  <depend>opencv</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
